<?php

/**
 * Implements hook_theme().
 */
function searchstudio_theme($existing, $type, $theme, $path) {
  return [
    // Name of the theme hook. This is used in the controller to trigger the hook.
    'searchstudio' => [
      'render element' => 'children',
      'template' => 'searchstudio',
      'path' => $path . '/templates'
    ],
  ];
}

/**
 * Implements hook_preprocess_page()
 */
function searchstudio_preprocess_page(&$variables) {
    $variables['#attached']['library'][] = 'searchstudio/searchstudio-app';
}
